# Generated by Django 5.1.6 on 2025-02-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_remove_movie_director_remove_movie_genre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_img',
        ),
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='movies/'),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
