# Generated by Django 5.1.6 on 2025-02-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_rename_movie_name_movie_name_remove_movie_movie_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('director', models.CharField(blank=True, max_length=200, null=True)),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('synopsis', models.TextField(blank=True, null=True)),
                ('spoiler', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='movies/')),
            ],
        ),
    ]
